### PR TITLE
Handling the continue cases for BDS retry

### LINKED ISSUE #368: [Bug]: BDS infinite retry not functional with inactive boot option at the end of queue
### Is there an existing issue for this?

- [X] I have searched existing issues

### Current Behavior

When booting with a given boot option list, with the newly introduced `PcdSupportInfiniteBootRetries` PCD set to true, the boot options should be iterated through indefinitely. However, due to the check for active boot options, the branch-out could cause the logic not going through the newly added wrap around logic and break out of the loop.

### Expected Behavior

With the newly introduced `PcdSupportInfiniteBootRetries` PCD set to true, the boot options should be iterated through indefinitely.

### Steps To Reproduce

1. Register several boot options with the last one registered not setting `LOAD_OPTION_ACTIVE`.
2. Let the BDS boot, make sure the let them all fail in the first pass.
3. System will iterate through the given option list, skip the inactive option and break out of the loop.

### Build Environment

```markdown
- OS(s): Ubuntu 22.04
- Tool Chain(s): GCC5
- Targets Impacted: AARCH64
```

### Version Information

```text
commit a5bf121fa89e0e65c0edfafac6eee88777214eda
```

### Urgency

Medium

### Are you going to fix this?

I will fix it

### Do you need maintainer feedback?

No maintainer feedback needed

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kuqin12**
## Description

The original change (https://github.com/microsoft/mu_basecore/pull/347) will not handle the use case when the last entry in the BootOptions being inactive, and the loop will break in one of the "continue" cases.

This change will ensure that continue statements redirect control to logic for handling infinite retry attempt support.

Fixes https://github.com/microsoft/mu_basecore/issues/368.

- [x] Impacts functionality?
  - **Functionality** - Does the change ultimately impact how firmware functions?
  - Examples: Add a new library, publish a new PPI, update an algorithm, ...
- [ ] Impacts security?
  - **Security** - Does the change have a direct security impact on an application,
    flow, or firmware?
  - Examples: Crypto algorithm change, buffer overflow fix, parameter
    validation improvement, ...
- [ ] Breaking change?
  - **Breaking change** - Will anyone consuming this change experience a break
    in build or boot behavior?
  - Examples: Add a new library class, move a module to a different repo, call
    a function in a new library class in a pre-existing module, ...
- [ ] Includes tests?
  - **Tests** - Does the change include any explicit test code?
  - Examples: Unit tests, integration tests, robot tests, ...
- [ ] Includes documentation?
  - **Documentation** - Does the change contain explicit documentation additions
    outside direct code modifications (and comments)?
  - Examples: Update readme file, add feature readme file, link to documentation
    on an a separate Web page, ...

## How This Was Tested

This is tested on FVP based virtual platform.

## Integration Instructions

N/A

### CODE REVIEW

**Review by apop5 — APPROVED** [review]

File: MdeModulePkg/Universal/BdsDxe/BdsEntry.c
Comment (makubacki) [inline MdeModulePkg/Universal/BdsDxe/BdsEntry.c:1]: @kuqin12 can you please update "The original change" to include the commit hash of the change you're talking about (I believe it's what originated in PR #347).

Also, please file a bug issue and mention "Fixes issue #\<num\>" in the PR description so it will be linked/closed by the PR. Also, add a "`type:bug`" label so the change will be recognized properly in the release notes.

Comment (kuqin12) [reply MdeModulePkg/Universal/BdsDxe/BdsEntry.c:1]: Thanks, all done.

File: MdeModulePkg/Universal/BdsDxe/BdsEntry.c [hunk 1]
```diff
@@ -390,7 +390,18 @@ BootBootOptions (
   //
   // Attempt boot each boot option
   //
-  for (Index = 0; Index < BootOptionCount; Index++) {
+  // MU_CHANGE [BEGINS]- Support infinite boot retries
+  for (Index = 0;; Index++) {
+    if (Index == BootOptionCount) {
+      if (PcdGetBool (PcdSupportInfiniteBootRetries)) {
+        // Resetting index back to -1 so loop increment will result in Index 0 for next iteration
```
Comment (makubacki) [inline MdeModulePkg/Universal/BdsDxe/BdsEntry.c]: I'd recommend dropping the -1 comment now.


```suggestion

```

**Comment by makubacki** [comment]
I made some adjustments to the PR description to help clarify the issue. Please correct if you'd like to change anything.

**Review by makubacki — APPROVED** [review]

**Review by cfernald — APPROVED** [review]
