### PR TITLE
Use gMuEventPreExitBootServicesGuid for SnpDxe to issue PxeShutdown

### LINKED ISSUE #520: [Bug]: SnpDxe should execute PxeShutdown before ExitBootServices
### Is there an existing issue for this?

- [X] I have searched existing issues

### Current Behavior

SnpDxe registers for an ExitBootServices callback and runs the PXE_OPCODE_SHUTDOWN and PXE_OPCODE_STOP commands for any network controllers that the driver is attached to. If the Bus Master Enable bit is cleared by PciBusDxe before this point, then completions returned by the network cards will be unreadable to their drivers during the shutdown sequence.

### Expected Behavior

Register the SnpDxe callback for gMuEventPreExitBootServicesGuid instead of gEfiEventExitBootServicesGuid to ensure the correct ordering:

1. ExitBootServices event
2. Network card shutdown sequence is completed
3. BME is disabled on PCI bridges (if configured)

### Steps To Reproduce

1. Ensure PcdDisableBMEonEBS is set to TRUE
2. Boot to OS from disk
3. When ExitBootServices is notified, BME will be disabled on PCI bridges before PxeShutdown is issued to any cards

### Build Environment

```markdown
- OS(s): Windows
- Tool Chain(s): GCC5
- Targets Impacted: DEBUG AARCH64
```

### Version Information

```text
Commit: 502c9a9eb29951fbc507514024e3cc574beb50c2
```

### Urgency

Medium

### Are you going to fix this?

I will fix it https://github.com/microsoft/mu_basecore/pull/522 

### Do you need maintainer feedback?

Maintainer feedback requested

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JoeLopez333**
## Description
Fixes https://github.com/microsoft/mu_basecore/issues/520

SnpDxe registers for an ExitBootServices callback and runs the PXE_OPCODE_SHUTDOWN and PXE_OPCODE_STOP commands for any network controllers that the driver is attached to. If the Bus Master Enable bit is cleared by PciBusDxe before this point, then completions returned by the network cards will be unreadable to their drivers during the shutdown sequence.

Register the SnpDxe callback for gMuEventPreExitBootServicesGuid instead of gEfiEventExitBootServicesGuid to ensure the correct ordering:

1. ExitBootServices event
2. Network card shutdown sequence is completed
3. BME is disabled on PCI bridges (if configured)

- [X] Impacts functionality?
  - **Functionality** - Does the change ultimately impact how firmware functions?
  - Examples: Add a new library, publish a new PPI, update an algorithm, ...
- [ ] Impacts security?
  - **Security** - Does the change have a direct security impact on an application,
    flow, or firmware?
  - Examples: Crypto algorithm change, buffer overflow fix, parameter
    validation improvement, ...
- [ ] Breaking change?
  - **Breaking change** - Will anyone consuming this change experience a break
    in build or boot behavior?
  - Examples: Add a new library class, move a module to a different repo, call
    a function in a new library class in a pre-existing module, ...
- [ ] Includes tests?
  - **Tests** - Does the change include any explicit test code?
  - Examples: Unit tests, integration tests, robot tests, ...
- [ ] Includes documentation?
  - **Documentation** - Does the change contain explicit documentation additions
    outside direct code modifications (and comments)?
  - Examples: Update readme file, add feature readme file, link to documentation
    on an a separate Web page, ...

## How This Was Tested

verified on ARM platform with two network cards

## Integration Instructions

N/A

### CODE REVIEW

File: NetworkPkg/SnpDxe/Snp.c [hunk 1]
```diff
@@ -655,7 +655,7 @@ SimpleNetworkDriverStart (
                     TPL_CALLBACK,
                     SnpNotifyExitBootServices,
                     Snp,
-                    &gEfiEventExitBootServicesGuid,
+                    &gMuEventPreExitBootServicesGuid,
```
Comment (os-d) [inline NetworkPkg/SnpDxe/Snp.c]: Can you add MU_CHANGE tags around these changes?

**Review by os-d — APPROVED** [review]

**Review by makubacki — APPROVED** [review]

**Review by cfernald — APPROVED** [review]
