### PR TITLE
[REBASE&FF] ReportStatusCode: Always cache protocol before usage

### LINKED ISSUE #1601: [Bug]: Potential TPL inversion in ReportStatusCodeLib (DXE and Runtime)
### Is there an existing issue for this?

- [x] I have searched existing issues

### Current Behavior

When the system asserts, it is possible that some platform will invoke report status code, to log telemetry, to print a message, etc. However, the assert could have happened at any TPL.

With the current implementation inside basecore, if this is the first time an RSC invoked from inside a module, it will try to locate the protocol before dispatching to the listeners. If the TPL is already at HIGH, the locate call could have failed or double faulted.

### Expected Behavior

Rather than trying to locate on the fly, the library should have attempted to locate the protocol inside the constructor, and register a callback if this is not there. Then the global protocol will be populated whenever the protocol is ready.

If an RSC call is invoked before protocol var is populated, we will have to drop it, just like it failed to locate the protocol.

### Steps To Reproduce

Invoke secure boot variable write and delete multiple times, it will trigger the event log to be full and cause an assert, which will then fail when trying to log a telemetry entry.

### Build Environment

```markdown
- OS(s):Win11
- Tool Chain(s): VS2022
- Targets Impacted: X64 & Aarch64
```

### Version Information

```text
Top of release.
```

### Urgency

High

### Are you going to fix this?

Someone else needs to fix it

### Do you need maintainer feedback?

No maintainer feedback needed

### Anything else?

This is needed on some physical platform shortly.

### PR DESCRIPTION
**Pull request by Javagedes**
## Description

This commit stops the library for querying the protocol database for the
status code protocol at the time of use of the library function. This
logic can result in a TPL inversion if the protocol has not yet been
located and the caller is running in a TPL higher then TPL_NOTIFY.

Instead, the protocol is now located during construction of the library
during driver startup. If the protocol is not found, then an on-protocol
install event is registered. A deconstructor is also added to close the
event in the case that the driver is unloaded before the protocol is
installed.

This PR is a rebase and fast forward as it includes a new test.

- [x] Impacts functionality?
- [ ] Impacts security?
- [ ] Breaking change?
- [ ] Includes tests?
- [ ] Includes documentation?

## How This Was Tested

1. The written unit test, which failed in the first commit, now passes after the second commit
2. Verified that the event callback is successfully executed in all drivers that run before the protocol is produced, including the DXE Core.
3. Verified the steps to reproduce specified in #1601 no longer reproduces.

## Integration Instructions

N/A

### CODE REVIEW

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c [hunk 1]
```diff
@@ -611,3 +611,69 @@ ReportDebugCodeEnabled (
...
+   @retval   none
+ **/
+VOID
+EFIAPI
+OnStatusCodeRuntimeProtocolInstalledNotification (
+  IN EFI_EVENT  Event,
+  IN VOID       *Context
+  )
+{
+  InternalGetReportStatusCode ();
```
Comment (apop5) [inline MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:632]: Should the event get closed? I think gEfiStatusCodeRuntimeProtocolGuid is only installed once...

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c [hunk 2]
```diff
@@ -611,3 +611,69 @@ ReportDebugCodeEnabled (
...
+  )
+{
+  EFI_EVENT   Event;
+  EFI_STATUS  Status;
+  VOID        *Registration;
+
+  InternalGetReportStatusCode ();
+
+  // If the Status Code Runtime Protocol is not found, register a notification event for when it is installed.
+  if ((mReportStatusCodeLibStatusCodeProtocol == NULL) && (gBS != NULL) && (gBS->CreateEvent != NULL) && (gBS->RegisterProtocolNotify != NULL)) {
```
Comment (apop5) [inline MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c]: if gBS is valid, then CreateEvent and RegisterProtocolNotify should also be valid

https://github.com/microsoft/mu_basecore/blob/release/202502/MdeModulePkg/Core/Dxe/DxeMain/DxeMain.c#L42

they are populated in the default structure (mBootServices )

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c (hunk 1 above)
Comment (Javagedes) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:632]: Ah yes. Thanks. Updated :)

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c (hunk 2 above)
Comment (Javagedes) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c]: Fair enough! Updated :)

**Review by os-d — APPROVED** [review]
Can you take this to edk2, too?

**Comment by Javagedes** [comment]
> Can you take this to edk2, too?

ya, I will. Figured we wanted this here first though

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c [hunk 3]
```diff
@@ -611,3 +611,75 @@ ReportDebugCodeEnabled (
...
+
+    @param  ImageHandle   The firmware allocated handle for the EFI image.
+    @param  SystemTable   A pointer to the EFI System Table.
+
+    @retval EFI_SUCCESS   The constructor always returns EFI_SUCCESS.
+
+**/
+EFI_STATUS
+EFIAPI
+DxeReportStatusCodeLibConstructor (
```
Comment (makubacki) [inline MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c]: A convenience function sometimes used for this pattern is `EfiCreateProtocolNotifyEvent()` in UefiLib. I'm not necessarily suggesting that you use it, and you'd have to refactor some logic slightly to do so, but it's an option.

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c (hunk 1 above)
Comment (makubacki) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:632]: If there is a reinstall, are you sure you'd want to keep using the older protocol instance?

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c [hunk 4]
```diff
@@ -611,3 +611,75 @@ ReportDebugCodeEnabled (
...
+                    NULL,
+                    &Event
+                    );
+
+    if (EFI_ERROR (Status)) {
+      DEBUG ((DEBUG_WARN, "DxeReportStatusCodeLibConstructor: CreateEvent failed: %r\n", Status));
+      return EFI_SUCCESS;
+    }
+
+    Status = gBS->RegisterProtocolNotify (
```
Comment (makubacki) [inline MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:682]: Perhaps printing on error to make use of the return code would be useful here too.

File: MdeModulePkg/Library/DxeReportStatusCodeLib/TestDxeReportStatusCodeLibTestApp.c [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+    DEBUG ((DEBUG_ERROR, "Failed in CreateUnitTestSuite for No TPL Inversion Tests\n"));
+    Status = EFI_OUT_OF_RESOURCES;
+    goto EXIT;
+  }
+
+  AddTestCase (NoTplInversionTestSuite, "Test ReportStatusCode TPL High", "TestReportStatusCodeTplHigh", TestReportStatusCodeDoesNotInvertTpl, NULL, NULL, SystemTable);
+
+  Status = RunAllTestSuites (Framework);
+
+EXIT:
```
Comment (makubacki) [inline MdeModulePkg/Library/DxeReportStatusCodeLib/TestDxeReportStatusCodeLibTestApp.c]: nit: Convention would usually have this be `Exit`

File: MdeModulePkg/Library/DxeReportStatusCodeLib/TestDxeReportStatusCodeLibTestApp.h [hunk 6]
```diff
@@ -0,0 +1,24 @@
+/** @file
+  UEFI based application for unit testing the DxeReportStatusCodeLib.
+
+  Copyright (c) Microsoft Corporation.
+  SPDX-License-Identifier: BSD-2-Clause-Patent
+
+**/
+
+#ifndef _TEST_DXE_REPORT_STATUS_CODE_LIB_H_
+#define _TEST_DXE_REPORT_STATUS_CODE_LIB_H_
```
Comment (makubacki) [inline MdeModulePkg/Library/DxeReportStatusCodeLib/TestDxeReportStatusCodeLibTestApp.h]:
```suggestion
#ifndef TEST_DXE_REPORT_STATUS_CODE_LIB_H_
#define TEST_DXE_REPORT_STATUS_CODE_LIB_H_

```

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c (hunk 1 above)
Comment (Javagedes) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:632]: As @apop5 mentioned, is this installed more than once? Or should I just be safe and do it anyway? Technically with the current implementation, it also only uses the first protocol found, regardless of future possible installations.

If that is the case, then I'd probably need to register the event callback even if we found a protocol during start up.

Comment (Javagedes) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:632]: Another benefit if we do it this way, is I can just remove the `InternalGetReportStatusCode` from all library functions, as we can just assume (is it safe to assume this?) that the protocol will be cached if it exists.

Comment (makubacki) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:632]: It is possible that it could be reinstalled simply because that's an option and we can't control all code that interacts with the protocol database out there.

The expectation is usually that what would you get from a current `LocateProtocol()` call is what would be used moving forward.

My understanding is that prior behavior would also freshly locate the protocol on a `ReportStatusCode()` invocation. If that's the case, it should continue to be supported.

Comment (makubacki) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:632]: Though, in the current implementation, it will still update the global through `InternalGetReportStatusCode()`, right?

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c (hunk 3 above)
Comment (Javagedes) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c]: This was a good idea and I tried it out after your suggestion, but one of the things it does is signal the event once. Since this library constructor is also called for the DXE_CORE, the event list is not fully set up and we end up asserting.

Due to this, I will be closing this without implementing.

File: MdeModulePkg/Library/DxeReportStatusCodeLib/TestDxeReportStatusCodeLibTestApp.c (hunk 5 above)
Comment (Javagedes) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/TestDxeReportStatusCodeLibTestApp.c]: Updated to `Exit`. Thanks!

File: MdeModulePkg/Library/DxeReportStatusCodeLib/TestDxeReportStatusCodeLibTestApp.h (hunk 6 above)
Comment (Javagedes) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/TestDxeReportStatusCodeLibTestApp.h]: Updated. Thanks!

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c (hunk 4 above)
Comment (Javagedes) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:682]: Added an error check and log for the register function also. Thanks!

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c (hunk 1 above)
Comment (Javagedes) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:632]: Hmm That is a good point. `InternalGetReportStatusCode` returns early if the cached protocol is already set. So this library does not currently ever update the protocol if a new one is registered.

I can update the event callback to update it regardless, if you wish. 

But I cannot update `InternalGetReportStatusCode` or we will try and re-locate the protocol every time, which will make us continue to hit the current TPL inversion error.

Comment (makubacki) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:632]: I'm a little concerned about the number of entries in the event database leaving this open too given it is linked against so many DXE modules. But I think that's technically the more robust behavior and I lean toward it if the reinstall case was previously supported to preserve that behavior.

Comment (makubacki) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:632]: Actually, looking at the current code, it does not locate when the global is non-null, so I think closing is fine since that's the precedent.

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c [hunk 7]
```diff
@@ -611,3 +611,80 @@ ReportDebugCodeEnabled (
...
+                    &gEfiStatusCodeRuntimeProtocolGuid,
+                    Event,
+                    &Registration
```
Comment (kuqin12) [inline MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:685]: I think we might need to make this `Registration` global and unregister is in a destructor. This is in case the driver unloads itself, then we will need leave a dangling pointer in the protocol DB.

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c [hunk 8]
```diff
@@ -611,3 +611,80 @@ ReportDebugCodeEnabled (
...
+  EFI_STATUS  Status;
+  VOID        *Registration;
+
+  InternalGetReportStatusCode ();
+
+  // If the Status Code Runtime Protocol is not found, register a notification event for when it is installed.
+  if ((mReportStatusCodeLibStatusCodeProtocol == NULL) && (gBS != NULL)) {
+    Status = gBS->CreateEvent (
+                    EVT_NOTIFY_SIGNAL,
+                    TPL_CALLBACK,
```
Comment (kuqin12) [inline MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:672]: nit: we probably can make this run at a higher level. But this is just to extend the coverage of RSC calls.

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c
Comment (kuqin12) [inline MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:46]: We need to remove this locate call. Otherwise, a call before our callback will still run into the same issue?

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c [hunk 9]
```diff
@@ -611,3 +611,80 @@ ReportDebugCodeEnabled (
...
+DxeReportStatusCodeLibConstructor (
+  IN EFI_HANDLE        ImageHandle,
+  IN EFI_SYSTEM_TABLE  *SystemTable
+  )
+{
+  EFI_EVENT   Event;
+  EFI_STATUS  Status;
+  VOID        *Registration;
+
+  InternalGetReportStatusCode ();
```
Comment (kuqin12) [inline MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:659]: And instead, we need to move the locate here.

File: MdeModulePkg/Library/DxeReportStatusCodeLib/TestDxeReportStatusCodeLibTestApp.c [hunk 10]
```diff
@@ -0,0 +1,84 @@
+/** @file
+  UEFI based application for unit testing the DxeReportStatusCodeLib.
```
Comment (kuqin12) [inline MdeModulePkg/Library/DxeReportStatusCodeLib/TestDxeReportStatusCodeLibTestApp.c:2]: I like the tests :)

File: MdeModulePkg/MdeModulePkg.dsc [hunk 11]
```diff
@@ -351,6 +351,15 @@
...
+  # MU_CHANGE [BEGIN] - Add constructor to cache protocol or register for protocol notification
+  MdeModulePkg/Library/DxeReportStatusCodeLib/TestDxeReportStatusCodeLibTestApp.inf {
+    <LibraryClasses>
+        UnitTestLib|UnitTestFrameworkPkg/Library/UnitTestLib/UnitTestLib.inf
+        UnitTestPersistenceLib|UnitTestFrameworkPkg/Library/UnitTestPersistenceLibNull/UnitTestPersistenceLibNull.inf
+        UnitTestResultReportLib|UnitTestFrameworkPkg/Library/UnitTestResultReportLib/UnitTestResultReportLibDebugLib.inf
+        UnitTestBootLib|UnitTestFrameworkPkg/Library/UnitTestBootLibNull/UnitTestBootLibNull.inf
+  }
+  # MU_CHANGE [END] - Add constructor to cache protocol or register for protocol notification
   MdeModulePkg/Library/RuntimeDxeReportStatusCodeLib/RuntimeDxeReportStatusCodeLib.inf
```
Comment (kuqin12) [inline MdeModulePkg/MdeModulePkg.dsc:363]: I think you will need to make the same change for this runtime instance.

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c
Comment (Javagedes) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:46]: I mentioned this in the PR comment, but this change merely follows the requested change in the attached issue and does not fully stop the possibility of a TPL inversion.

As this PR mentions, it is still possible to have an inversion if a driver is running before any Status Code protocol has been globally installed, and calls `ReportStatusCode` while in a TPL higher than `TPL_NOTIFY`.

I'm more than happy to fundamentally change the logic of this to only set the global via the constructor & protocol install event, removing the LocateProtocol from `ReportStatusCode` all together.

If that is your preference, just let me know.

Comment (kuqin12) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:46]: So the proposal in the issue is to remove the locate on the fly and move it to the constructor only, so that we do not run into the same issue. We are already changing the logic quite a bit and adding a brand new test, might as well fully prevent the inversion from happening.

Comment (Javagedes) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:46]: Sounds good. Seems like I misunderstood the proposal. I will make the changes and re request reviews :)

Comment (kuqin12) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:46]: Thanks a lot!

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c (hunk 7 above)
Comment (Javagedes) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:685]: Cached the `Event`, not the registration, so that I can call `gBS->CloseEvent(...)` in the deconstructor.

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c (hunk 8 above)
Comment (Javagedes) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:672]: It can run at any level up to TPL_NOTIFY. If you have a preference, I will update. Just let me know which one you want.

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c (hunk 9 above)
Comment (Javagedes) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:659]: `InternalGetReportStatusCode ();` is what does the locate. so this portion is already correct.

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c
Comment (Javagedes) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:46]: Per this conversation and offline conversation, I am updating this library to no longer attempt to get the report status code protocol (if not found) during a `ReportStatusCode` call. This will completely prevent the possibility of TPL inversion.

After changes, we do an initial `GetProtocol` in the constructor. If it fails to find the protocol, we instead create an on protocol event callback to cache the protocol.

The event will only ever be called once (uninstalling itself).

If the library is unloaded and the event has not been called, we will close the event.

File: MdeModulePkg/MdeModulePkg.dsc (hunk 11 above)
Comment (Javagedes) [reply MdeModulePkg/MdeModulePkg.dsc:363]: This library instance is the backing library for `DXE_CORE`, `DXE_DRIVER`, and `DXE_RUNTIME_DRIVER` (among multiple others), so this should suffice.

**Comment by Javagedes** [comment]
I have re-requested all reviews, as I have made a fundamental change to the pull request.

File: MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c (hunk 8 above)
Comment (makubacki) [reply MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c:672]: I assume the request was to prioritize setting the global here to preempt TPL_CALLBACK notifications.

**Review by makubacki — APPROVED** [review]

**Review by kuqin12 — APPROVED** [review]

**Review by kuqin12 — APPROVED** [review]

**Review by apop5 — APPROVED** [review]
