### PR TITLE
MdeModulePkg: PciHostBridgeDxe: ignore TypeIo

### LINKED ISSUE #444: [Bug]: Continue gracefully on unavailable resource spaces
### Is there an existing issue for this?

- [X] I have searched existing issues

### Current Behavior

On certain platforms, such as ARM based systems, there is not any available IO space.

Currently the PCI driver will exit the resource allocation if any of the requested resources are not available.

### Expected Behavior

The request is that, if an endpoint is requesting IO space, there should be a way to continue gracefully without allocating any IO resources.

### Steps To Reproduce

Build a system firmware with top of basecore and flash on to a device that has the above behavior on requesting IO spaces.

Once the endpoint requested IO spaces, the subsequent endpoint will no longer be able to allocate any resources.

### Build Environment

```markdown
- OS(s): Ubuntu 22.04 and 20.04
- Tool Chain(s): GCC5
- Targets Impacted: RELEASE, DEBUG
```

### Version Information

```text
Top of release/202302
```

### Urgency

Medium

### Are you going to fix this?

Someone else needs to fix it

### Do you need maintainer feedback?

No maintainer feedback needed

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Javagedes**
## Description

Throughout PciHostBridgeDxe, functions iterate through all entries in the PCI_RESOURCE_TYPE enum.  However TypeIo only applies for x86_64 platforms. This changes the starting point of the PCI_RESOURCE_TYPE enum loops from 0 to PCI_RESOURCE_TYPE_ENUM_START and conditionally sets that value to TypeIo or TypeMem32 based on if the platform is x86_64 or not.

closes #444

- [x] Impacts functionality?
  - **Functionality** - Does the change ultimately impact how firmware functions?
  - Examples: Add a new library, publish a new PPI, update an algorithm, ...
- [ ] Impacts security?
  - **Security** - Does the change have a direct security impact on an application,
    flow, or firmware?
  - Examples: Crypto algorithm change, buffer overflow fix, parameter
    validation improvement, ...
- [ ] Breaking change?
  - **Breaking change** - Will anyone consuming this change experience a break
    in build or boot behavior?
  - Examples: Add a new library class, move a module to a different repo, call
    a function in a new library class in a pre-existing module, ...
- [ ] Includes tests?
  - **Tests** - Does the change include any explicit test code?
  - Examples: Unit tests, integration tests, robot tests, ...
- [ ] Includes documentation?
  - **Documentation** - Does the change contain explicit documentation additions
    outside direct code modifications (and comments)?
  - Examples: Update readme file, add feature readme file, link to documentation
    on an a separate Web page, ...

## How This Was Tested

Will be platform tested

## Integration Instructions

N/A

### CODE REVIEW

File: MdeModulePkg/Bus/Pci/PciHostBridgeDxe/PciHostResource.h [hunk 1]
```diff
@@ -24,6 +24,15 @@ typedef enum {
   TypeMax
 } PCI_RESOURCE_TYPE;
 
+// MU_CHANGE begin
+// Only x86_64 has IO resource
+#if defined(__x86_64__)
```
Comment (kuqin12) [inline MdeModulePkg/Bus/Pci/PciHostBridgeDxe/PciHostResource.h]: Can we use the `MDE_CPU_*` to be EFI consistent?

Comment (Javagedes) [reply MdeModulePkg/Bus/Pci/PciHostBridgeDxe/PciHostResource.h]: Updated to MDE_CPU_X64

File: MdeModulePkg/Bus/Pci/PciHostBridgeDxe/PciHostResource.h [hunk 2]
```diff
@@ -24,6 +24,15 @@ typedef enum {
   TypeMax
 } PCI_RESOURCE_TYPE;
 
+// MU_CHANGE begin
+// Only processor type X64 has IO resource
+#if defined (MDE_CPU_X64)
```
Comment (makubacki) [inline MdeModulePkg/Bus/Pci/PciHostBridgeDxe/PciHostResource.h]: Was IA32 intentionally excluded?

```suggestion
#if defined (MDE_CPU_IA32) || defined (MDE_CPU_X64)

```

Comment (Javagedes) [reply MdeModulePkg/Bus/Pci/PciHostBridgeDxe/PciHostResource.h]: Hi Michael. This makes sense. Thanks for the suggestion!

**Review by kuqin12 — APPROVED** [review]

**Review by makubacki — APPROVED** [review]
